export enum InvitationProvidersEnum {
  INVITATION_REPOSITORY = 'INVITATION_REPOSITORY',
  CREATE_INVITATION_USE_CASE = 'CREATE_INVITATION_USE_CASE',
  ACCEPT_INVITATION_USE_CASE = 'ACCEPT_INVITATION_USE_CASE',
  GET_INVITATION_BY_TOKEN_USE_CASE = 'GET_INVITATION_BY_TOKEN_USE_CASE',
  LIST_INVITATIONS_USE_CASE = 'LIST_INVITATIONS_USE_CASE',
}
