export enum AuthUseCasesEnum {
  SETUP_USE_CASE = 'SETUP_USE_CASE',
  SIGN_IN_USE_CASE = 'SIGN_IN_USE_CASE',
  REFRESH_TOKEN_USE_CASE = 'REFRESH_TOKEN_USE_CASE',
  TOKEN_REVOCATION_REPOSITORY = 'TOKEN_REVOCATION_REPOSITORY',
  AUTH_SERVICE = 'AUTH_SERVICE',
}
