export enum McpProvidersEnum {
  API_KEY_REPOSITORY = 'API_KEY_REPOSITORY',
  VALIDATE_API_KEY_USE_CASE = 'VALIDATE_API_KEY_USE_CASE',
  CREATE_API_KEY_USE_CASE = 'CREATE_API_KEY_USE_CASE',
  LIST_FOLDERS_USE_CASE = 'MCP_LIST_FOLDERS_USE_CASE',
  LIST_DOCUMENTS_USE_CASE = 'MCP_LIST_DOCUMENTS_USE_CASE',
  READ_DOCUMENT_USE_CASE = 'MCP_READ_DOCUMENT_USE_CASE',
  MCP_SERVER_SERVICE = 'MCP_SERVER_SERVICE',
}
