export enum GroupProvidersEnum {
  GROUP_REPOSITORY = 'GROUP_REPOSITORY',
  CREATE_GROUP_USE_CASE = 'CREATE_GROUP_USE_CASE',
  LIST_GROUPS_USE_CASE = 'LIST_GROUPS_USE_CASE',
  GET_GROUP_BY_ID_USE_CASE = 'GET_GROUP_BY_ID_USE_CASE',
  UPDATE_GROUP_USE_CASE = 'UPDATE_GROUP_USE_CASE',
  DELETE_GROUP_USE_CASE = 'DELETE_GROUP_USE_CASE',
  ADD_USER_TO_GROUP_USE_CASE = 'ADD_USER_TO_GROUP_USE_CASE',
  REMOVE_USER_FROM_GROUP_USE_CASE = 'REMOVE_USER_FROM_GROUP_USE_CASE',
}
