export enum FolderProvidersEnum {
  FOLDER_REPOSITORY = 'FOLDER_REPOSITORY',
  CREATE_FOLDER_USE_CASE = 'CREATE_FOLDER_USE_CASE',
  GET_FOLDER_TREE_USE_CASE = 'GET_FOLDER_TREE_USE_CASE',
  GET_FOLDER_BY_ID_USE_CASE = 'GET_FOLDER_BY_ID_USE_CASE',
  UPDATE_FOLDER_USE_CASE = 'UPDATE_FOLDER_USE_CASE',
  DELETE_FOLDER_USE_CASE = 'DELETE_FOLDER_USE_CASE',
}
