export enum DocumentProvidersEnum {
  DOCUMENT_REPOSITORY = 'DOCUMENT_REPOSITORY',
  CREATE_DOCUMENT_USE_CASE = 'CREATE_DOCUMENT_USE_CASE',
  GET_DOCUMENT_BY_ID_USE_CASE = 'GET_DOCUMENT_BY_ID_USE_CASE',
  UPDATE_DOCUMENT_USE_CASE = 'UPDATE_DOCUMENT_USE_CASE',
  DELETE_DOCUMENT_USE_CASE = 'DELETE_DOCUMENT_USE_CASE',
  LIST_DOCUMENTS_BY_FOLDER_USE_CASE = 'LIST_DOCUMENTS_BY_FOLDER_USE_CASE',
}
