export enum CollaborationProvidersEnum {
  DOCUMENT_SYNC_SERVICE = 'DOCUMENT_SYNC_SERVICE',
  DOCUMENT_UPDATE_REPOSITORY = 'DOCUMENT_UPDATE_REPOSITORY',
  DOCUMENT_SNAPSHOT_REPOSITORY = 'DOCUMENT_SNAPSHOT_REPOSITORY',
  LOAD_DOCUMENT_USE_CASE = 'LOAD_DOCUMENT_USE_CASE',
  APPLY_UPDATE_USE_CASE = 'APPLY_UPDATE_USE_CASE',
  PERSIST_SNAPSHOT_USE_CASE = 'PERSIST_SNAPSHOT_USE_CASE',
}
