export enum PermissionProvidersEnum {
  PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY',
  SET_PERMISSION_USE_CASE = 'SET_PERMISSION_USE_CASE',
  GET_PERMISSION_MATRIX_USE_CASE = 'GET_PERMISSION_MATRIX_USE_CASE',
  GET_FOLDER_PERMISSIONS_USE_CASE = 'GET_FOLDER_PERMISSIONS_USE_CASE',
}
