export enum ApiKeyProvidersEnum {
  API_KEY_REPOSITORY = 'API_KEY_REPOSITORY',
  VALIDATE_API_KEY_USE_CASE = 'VALIDATE_API_KEY_USE_CASE',
  CREATE_API_KEY_USE_CASE = 'CREATE_API_KEY_USE_CASE',
  LIST_API_KEYS_USE_CASE = 'LIST_API_KEYS_USE_CASE',
  REVOKE_API_KEY_USE_CASE = 'REVOKE_API_KEY_USE_CASE',
}
